name: PHP Lint

# Événement déclencheur
on:
  push:
    branches:
      - develop

jobs:
  lint:
    # Exécuter sur le runner self-hosté
    runs-on: self-hosted

    steps:
      # Extraire le code source
      - name: Checkout code
      - run: je run le ssh du truc https github cloud
