name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    name: PHP Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP Lint
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file"
          done

  build:
    runs-on: ubuntu-latest
    needs: lint
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t loanlebrave/my-site:latest .

  push:
    runs-on: ubuntu-latest
    needs: build
    name: Push Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push loanlebrave/my-site:latest

