name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  lint:

    runs-on: self-hosted
    name: PHP Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: PHP Lint
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file"
          done 
