name: PHP Lint

# Événement déclencheur
on:
  push:
    branches:
      - develop

jobs:
  lint:
    # Exécuter sur le runner self-hosté
    runs-on: self-hosted

    steps:
      # Extraire le code source
      - name: Checkout code
        uses: action/checkout@v2
      
      - name: Run custom command
        run: echo "je runzz le ssh du truc https github cloud"
